### ISSUE TITLE
Pre-Alpha checklist

### ISSUE THREAD

**Issue by cevian** [timescale/pgvectorscale#10]
# extension

- [x] merge pq
- [x] merge refactor
- [x] get rid of full-fidelity vectors inside the index for pq
- [x] debian packaging
- [x] remove distances from index
- [x] rename repo and extension to timescale-vector
- [x] what is the right name for the index (its tsv for now)
- [x] review the parameter names
- [x] do we need to do anything for other distance types?

# python 
- [x] add vector extension into setup
- [x] add tsv index to lib
- [ ] add tsv index as default to langchain in at least from_documents
- [x] add tsv index as default to llama index 
- [x] Decide on default tsv index parameters for LangChain and LlamaIndex
- [x] make prs for lanchgchain and llama index

```[tasklist]
### Tasks
```
